version: "3.8"

networks:
    web:
    banco:
    fila:

volumes:
    dados:
        driver: local

services:
    database:
        image: postgres:14.3
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        volumes:
            - dados:/var/lib/postgresql/data
            - ./scripts/estrutura.sql:/docker-entrypoint-initdb.d/estrutura.sql
        networks:
            - banco

    frontend:
        image: nginx:1.21.6
        volumes:
            - ./web:/usr/share/nginx/html
        ports:
            - 80:80
        networks:
            - web
        depends_on:
            - engine

    engine:
        build: engine
        volumes:
            - ./engine:/engine
        working_dir: /engine
        command: engine.py
        ports:
            - 8080:8080
        networks:
            - web
            - banco
            - fila
        depends_on:
            - database
            - queue
        environment:
            - DB_NAME=email_sender

    queue:
        image: redis:7.0
        networks:
            - fila

    worker:
        build: worker
        volumes:
            - ./worker:/worker
        working_dir: /worker
        command: worker.py
        networks:
            - fila
        depends_on:
            - queue
